apiVersion: v1
kind: pod
metadata:
  name: pod
  labels:
    app: volume
    type: web
spec:
  containers:
    name: ubuntu
    image: ubuntu
    volumeMounts:
      name: data
      mountPath: /tmp/
  volumes:
    name: data
    hostPath:
      path: /hostvolume
      type: DirectoryORCreate
